
DROP DATABASE IF EXISTS TEST;
CREATE DATABASE TEST;

USE TEST;

-- CREAZIONE DELLE TABLE

-- UTENTE
CREATE TABLE UTENTE (
    Username VARCHAR(30) PRIMARY KEY,
    CodiceFiscale VARCHAR(30),
    Password VARCHAR(30),
    Luogo VARCHAR(30),
    Data VARCHAR(30)
) engine=InnoDB;

SELECT * FROM UTENTE;
