-- Active: 1771787311626@@localhost@3308@test

DROP DATABASE IF EXISTS TEST;
CREATE DATABASE TEST;

USE TEST;

-- CREAZIONE DELLE TABLE

-- UTENTE
CREATE TABLE UTENTE (
    Username VARCHAR(30) PRIMARY KEY,
    CodiceFiscale VARCHAR(30),
    Password VARCHAR(30),
    Luogo VARCHAR(30),
    Data VARCHAR(30)
) engine=InnoDB;

CREATE TABLE EMAIL (
    Username VARCHAR(30),
    Email VARCHAR(255),
    PRIMARY KEY(Username,Email),
    FOREIGN KEY(Username) REFERENCES UTENTE(Username)
)

SELECT * FROM UTENTE;
SELECT Password FROM UTENTE WHERE Username = '814';